ENH: Create semantic type for virsorter2 database
bokulich-lab/q2-virsorter2 pull request #2
Opened 2024-06-19 09:08 UTC by ChristosMatzoros

2024-06-21 13:59 UTC, Sann5 commented
Sorry, I haven't had time to review this @ChristosMatzoros. I'm gone thins Monday and maybe Tuesday so if it's urgent maybe you can ask someone else to do it. I will also prioritize finishing up stuff next week since it's my last one.

2024-06-25 14:59 UTC, VinzentRisch requested changes
Looks very good. See some changes below.

2024-06-25 14:59 UTC, VinzentRisch commented on README.md
> +mamba create -n q2-viromics -c conda-forge -c bioconda -c  https://packages.qiime2.org/qiime2/2023.5/tested/ -c defaults q2-types numpy=1.23.5 q2cli virsorter=2 "python=3.8" scikit-learn=0.22.1 panda
```suggestion
mamba create -n q2-viromics -c conda-forge -c bioconda -c  https://packages.qiime2.org/qiime2/2023.5/tested/ -c defaults q2-types numpy=1.23.5 q2cli virsorter=2 "python=3.8" scikit-learn=0.22.1 pandas seaborn hmmer==3.3 prodigal=2.6 screed=1 ruamel.yaml click pip last ncbi-genome-download checkv pyhmmer
```

2024-06-25 14:59 UTC, VinzentRisch commented on setup.py
> +description = "A QIIME 2 plugin for viromics identification and analysis."
```suggestion
description = "A QIIME 2 plugin for the identification and analysis of viral sequences."
```
identification of viromics does not make sense. Mine is a suggestion maybe you find something better.

2024-06-26 08:20 UTC, ChristosMatzoros commented
Hey @VinzentRisch,

I did the corrections, you can have a look.

2024-06-26 09:47 UTC, VinzentRisch approved these changes
Looks good to me.

2024-06-26 09:49 UTC, merged